/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Scenario, TimelineStep, Card, PositionName, Player } from '../types';

// Helper to create cards
const createCard = (value: string, suit: string): Card => ({
  value: value as any,
  suit: suit as any,
  isFacedown: false,
});

// Helper to generate UUIDs
const uuid = () => Math.random().toString(36).substring(2, 9);

// Create standard starting players
export const getInitialPlayers = (): Player[] => [
  {
    id: 1,
    position: 'SB',
    name: 'Small Blind',
    cards: [],
    chips: '100 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: false,
    isHighlighted: false,
  },
  {
    id: 2,
    position: 'BB',
    name: 'Big Blind',
    cards: [],
    chips: '100 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: false,
    isHighlighted: false,
  },
  {
    id: 3,
    position: 'UTG',
    name: 'UTG Player',
    cards: [],
    chips: '100 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: false,
    isHighlighted: false,
  },
  {
    id: 4,
    position: 'UTG+1',
    name: 'UTG+1 Player',
    cards: [],
    chips: '120 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: false,
    isHighlighted: false,
  },
  {
    id: 5,
    position: 'UTG+2',
    name: 'UTG+2 Player',
    cards: [],
    chips: '85 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: false,
    isHighlighted: false,
  },
  {
    id: 6,
    position: 'LJ',
    name: 'Lojack',
    cards: [],
    chips: '100 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: false,
    isHighlighted: false,
  },
  {
    id: 7,
    position: 'HJ',
    name: 'Hijack',
    cards: [],
    chips: '150 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: false,
    isHighlighted: false,
  },
  {
    id: 8,
    position: 'CO',
    name: 'Cutoff (Hero)',
    cards: [],
    chips: '100 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: false,
    isHighlighted: false,
  },
  {
    id: 9,
    position: 'BTN',
    name: 'Button',
    cards: [],
    chips: '100 BB',
    currentAction: 'NONE',
    isFolded: false,
    isActive: false,
    isDealer: true, // BTN starts as dealer by default
    isHighlighted: false,
  },
];

export const PRESET_SCENARIOS: Scenario[] = [
  {
    name: 'سناریوی پیش‌فرض: دفاع در برابر اوپن ریز (Hero vs CO)',
    description: 'سناریوی پیش‌فرض طراحی سیستم - آموزش گام به گام اوپن ریز پوزیشن CO و بازی پس از فلاپ.',
    steps: [
      {
        id: uuid(),
        type: 'SET_DEALER',
        seatId: 9, // BTN
        description: 'تنظیم دکمه دیلر روی پوزیشن BTN',
      },
      {
        id: uuid(),
        type: 'SET_CARDS',
        seatId: 8, // CO
        playerCards: [createCard('A', 'H'), createCard('K', 'D')], // Ah Kd
        description: 'توزیع کارت هیرو در کات‌آف: Ah Kd',
      },
      {
        id: uuid(),
        type: 'SET_CARDS',
        seatId: 3, // UTG
        playerCards: [createCard('T', 'S'), createCard('T', 'C')], // Ts Tc
        description: 'توزیع کارت بازیکن UTG: Ts Tc',
      },
      {
        id: uuid(),
        type: 'SET_TEXT',
        customText: 'فاز پری‌فلاپ - بازی با اوپن ریز پوزیشن UTG آغاز می‌شود.',
        description: 'نمایش توضیح پری‌فلاپ',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 3,
        description: 'زوم دوربین روی پوزیشن UTG',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 3,
        actionType: 'RAISE',
        actionAmount: '2.5 BB',
        description: 'بازیکن UTG اوپن ریز می‌کند به اندازه 2.5 BB',
      },
      {
        id: uuid(),
        type: 'HIGHLIGHT_SEAT',
        seatId: 3,
        description: 'هایلایت پوزیشن UTG',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 2000,
        description: 'مکث',
      },
      {
        id: uuid(),
        type: 'SET_TEXT',
        customText: 'پوزیشن‌های میانی فولد می‌دهند و نوبت به هیرو در CO می‌رسد.',
        description: 'توضیح فولد پوزیشن‌های میانی',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 4,
        actionType: 'FOLD',
        description: 'بازیکن UTG+1 فولد می‌دهد',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 5,
        actionType: 'FOLD',
        description: 'بازیکن UTG+2 فولد می‌دهد',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 6,
        actionType: 'FOLD',
        description: 'بازیکن LJ فولد می‌دهد',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 7,
        actionType: 'FOLD',
        description: 'بازیکن HJ فولد می‌دهد',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 8,
        description: 'زوم روی هیرو (CO)',
      },
      {
        id: uuid(),
        type: 'HIGHLIGHT_SEAT',
        seatId: 8,
        description: 'هایلایت پوزیشن هیرو',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 8,
        actionType: 'CALL',
        actionAmount: '2.5 BB',
        description: 'هیرو با کارت Ah Kd ریز را کال می‌کند',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 2000,
        description: 'مکث',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 9,
        actionType: 'FOLD',
        description: 'پوزیشن BTN فولد می‌دهد',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 1,
        actionType: 'FOLD',
        description: 'اسمال بلایند فولد می‌دهد',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 2,
        actionType: 'FOLD',
        description: 'بیگ بلایند فولد می‌دهد',
      },
      {
        id: uuid(),
        type: 'SET_POT',
        potValue: '6.5 BB',
        description: 'تنظیم میزان پات به 6.5 BB',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 'cards',
        description: 'زوم روی کارت‌های زمین (Community Cards)',
      },
      {
        id: uuid(),
        type: 'REVEAL_COMMUNITY',
        cardsToReveal: [createCard('A', 'D'), createCard('K', 'C'), createCard('7', 'S')],
        description: 'رو شدن کارت‌های فلاپ: Ad Kc 7s',
      },
      {
        id: uuid(),
        type: 'SET_TEXT',
        customText: 'فلاپ رو می‌شود: Ad Kc 7s. هیرو صاحب دو جفت (Two Pair) می‌شود.',
        description: 'توضیح فلاپ',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 2500,
        description: 'مکث روی فلاپ',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 3,
        description: 'زوم روی UTG',
      },
      {
        id: uuid(),
        type: 'HIGHLIGHT_SEAT',
        seatId: 3,
        description: 'هایلایت UTG برای تصمیم‌گیری',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 3,
        actionType: 'CHECK',
        description: 'بازیکن UTG چک می‌دهد',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 1500,
        description: 'مکث',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 8,
        description: 'زوم روی هیرو',
      },
      {
        id: uuid(),
        type: 'HIGHLIGHT_SEAT',
        seatId: 8,
        description: 'هایلایت هیرو برای اکشن',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 8,
        actionType: 'BET',
        actionAmount: '3.5 BB',
        description: 'هیرو با داشتن تاپ تو پیر مقدار 3.5 BB شرط می‌بندد (Bet)',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 2000,
        description: 'مکث',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 3,
        description: 'زوم روی UTG',
      },
      {
        id: uuid(),
        type: 'HIGHLIGHT_SEAT',
        seatId: 3,
        description: 'هایلایت UTG',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 3,
        actionType: 'FOLD',
        description: 'بازیکن UTG فولد می‌دهد و دست به نفع هیرو به پایان می‌رسد',
      },
      {
        id: uuid(),
        type: 'SET_TEXT',
        customText: 'پیروزی هیرو! بازیکن UTG فولد داد و هیرو پات را برنده شد.',
        description: 'پایان بازی و برد هیرو',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 'table',
        description: 'بازگشت دوربین به نمای کامل میز',
      },
    ],
  },
  {
    name: 'مثال آموزشی ۲: آل-این قبل از فلاپ (Preflop All-in Block)',
    description: 'آموزش شرایط آل-این و مقایسه دو دست قوی قبل از فلاپ (کارت‌های آس شاه در برابر جفت سرباز).',
    steps: [
      {
        id: uuid(),
        type: 'SET_DEALER',
        seatId: 8, // CO
        description: 'تنظیم دیلر روی CO',
      },
      {
        id: uuid(),
        type: 'SET_CARDS',
        seatId: 9, // BTN
        playerCards: [createCard('A', 'S'), createCard('K', 'S')], // As Ks
        description: 'کارت دکمه: As Ks',
      },
      {
        id: uuid(),
        type: 'SET_CARDS',
        seatId: 2, // BB
        playerCards: [createCard('J', 'H'), createCard('J', 'D')], // Jh Jd
        description: 'کارت بیگ بلایند: Jh Jd',
      },
      {
        id: uuid(),
        type: 'SET_TEXT',
        customText: 'یک موقعیت حساس: آس شاه هم‌خال در برابر جفت سرباز قبل از فلاپ.',
        description: 'توضیحات دست دوم',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 9,
        description: 'زوم روی دکمه',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 9,
        actionType: 'RAISE',
        actionAmount: '3 BB',
        description: 'دکمه اوپن ریز می‌کند به اندازه 3 BB',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 1500,
        description: 'مکث',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 2,
        description: 'زوم روی بیگ بلایند',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 2,
        actionType: 'RAISE',
        actionAmount: '11 BB',
        description: 'بیگ بلایند با جفت سرباز 3-بت می‌کند به 11 BB',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 1500,
        description: 'مکث',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 9,
        description: 'زوم روی دکمه',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 9,
        actionType: 'ALL_IN',
        actionAmount: '100 BB',
        description: 'دکمه آل-این می‌کند به اندازه 100 BB!',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 1500,
        description: 'مکث',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 2,
        description: 'زوم روی بیگ بلایند',
      },
      {
        id: uuid(),
        type: 'PLAYER_ACTION',
        seatId: 2,
        actionType: 'ALL_IN',
        actionAmount: '100 BB',
        description: 'بیگ بلایند کال می‌کند! آل این تمام عیار.',
      },
      {
        id: uuid(),
        type: 'SET_POT',
        potValue: '200.5 BB',
        description: 'بروزرسانی پات به 200.5 BB',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 'cards',
        description: 'زوم روی کارت‌های زمین',
      },
      {
        id: uuid(),
        type: 'REVEAL_COMMUNITY',
        cardsToReveal: [createCard('K', 'H'), createCard('7', 'C'), createCard('2', 'D'), createCard('Q', 'S'), createCard('5', 'C')],
        description: 'رو شدن کارت‌های زمین: Kh 7c 2d Qs 5c',
      },
      {
        id: uuid(),
        type: 'SET_TEXT',
        customText: 'زمین شاه آورد و بلایند با یک پیر شاه برنده شد!',
        description: 'برد پیر آس شاه',
      },
      {
        id: uuid(),
        type: 'DELAY',
        delayMs: 3000,
        description: 'پایان سناریو',
      },
      {
        id: uuid(),
        type: 'CAMERA_ZOOM',
        zoomTarget: 'table',
        description: 'نمای کامل میز',
      },
    ],
  },
];
